Rails:
  Enabled: true

AllCops:
  TargetRubyVersion: 2.5.1
  Exclude:
     - vendor/**/*
     - bin/*
     - db/**/*
     - spec/rails_helper.rb

Metrics/LineLength:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - spec/**/*

# If it is not excluded, request's spec fails
Rails/HttpPositionalArguments:
  Exclude:
    - spec/requests/*
